sonar.projectKey=DISPLAY_PNR_CLIENT_COMPILED
sonar.working.directory=C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1
sonar.pullrequest.cache.basepath=C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1
sonar.sources=\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\.vs\\WpfBrowserApp1\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\.vs\\WpfBrowserApp1\\v17\\DocumentLayout.json"

CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.projectKey=DISPLAY_PNR_CLIENT_COMPILED:CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9
CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.projectName=WpfBrowserApp1
CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.projectBaseDir=C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1
CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.sourceEncoding=utf-8
CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.tests=
CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.sources=\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\App.xaml",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\App.xaml.cs",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Page1.xaml.cs",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Properties\\AssemblyInfo.cs",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Properties\\Resources.resx",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Properties\\Settings.settings",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Properties\\app.manifest",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\WpfBrowserApp1_TemporaryKey.pfx",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Page1.xaml",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Bundle.config",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Home.aspx",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\packages.config",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Web.config",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Web.Debug.config",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\bootstrap-grid.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\bootstrap-grid.min.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\bootstrap-reboot.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\bootstrap-reboot.min.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\bootstrap.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\bootstrap.min.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Content\\Site.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\AppGatewayStyle.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\bootstrap.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\Common.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\Controls.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\elastislide.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\eStaff.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\flexslider.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\ie.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\ImageSliderStyle.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\jquery-ui.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\jquery.calendars.picker.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\main-style.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\main-style1.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\PageStylesheet.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\responsive.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\SaudiACommon.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\SaudiASeattle.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\style.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\Stylesheet1.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\SVCalendar.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\SVNewTP.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\CSS\\tweet.css",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\bootstrap.bundle.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\bootstrap.bundle.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\bootstrap.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\bootstrap.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\index.d.ts",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\jquery-3.0.0-vsdoc.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\jquery-3.0.0.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\jquery-3.0.0.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\jquery-3.0.0.slim.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\jquery-3.0.0.slim.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\popper-utils.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\popper-utils.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\popper.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\popper.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\esm\\popper-utils.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\esm\\popper-utils.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\esm\\popper.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\esm\\popper.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\index.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\umd\\popper-utils.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\umd\\popper-utils.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\umd\\popper.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\umd\\popper.min.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\methods\\defaults.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\methods\\destroy.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\methods\\disableEventListeners.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\methods\\enableEventListeners.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\methods\\placements.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\methods\\update.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\applyStyle.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\arrow.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\computeStyle.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\flip.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\hide.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\index.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\inner.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\keepTogether.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\offset.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\preventOverflow.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\modifiers\\shift.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\clockwise.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\computeAutoPlacement.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\debounce.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\find.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\findCommonOffsetParent.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\findIndex.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getBordersSize.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getBoundaries.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getBoundingClientRect.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getClientRect.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getFixedPositionOffsetParent.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getOffsetParent.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getOffsetRect.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getOffsetRectRelativeToArbitraryNode.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getOppositePlacement.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getOppositeVariation.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getOuterSizes.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getParentNode.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getPopperOffsets.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getReferenceNode.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getReferenceOffsets.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getRoot.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getRoundedOffsets.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getScroll.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getScrollParent.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getStyleComputedProperty.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getSupportedPropertyName.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getViewportOffsetRectRelativeToArtbitraryNode.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getWindow.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\getWindowSizes.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\includeScroll.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\index.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isBrowser.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isFixed.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isFunction.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isIE.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isModifierEnabled.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isModifierRequired.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isNumeric.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\isOffsetContainer.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\removeEventListeners.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\runModifiers.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\setAttributes.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\setStyles.js",\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\WpfBrowserApp1\\Scripts\\src\\utils\\setupEventListeners.js"

CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\.sonarqube\\out\\1"
CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\.sonarqube\\out\\1\\Issues.json"

CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9.sonar.working.directory=C:\\Users\\hasan\\OneDrive\\Desktop\\test\\WpfBrowserApp1\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=https://sonarv10.jawda.ismena.me
sonar.visualstudio.enable=false

sonar.modules=CEB4C3E9-4BB5-4EBF-978E-A1E33C5DB6E9

